version: '3.8'

services:
  container-entra-auth:
    image: container-entra-auth:latest
    ports:
      - "8087:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=k8s
      - AZURE_CLIENT_ID=9f6cf3b0-c7fe-4220-86fd-a58ac086a692
      - AZURE_CLIENT_SECRET=changeme
      - AZURE_TENANT_ID=4f402a0a-52d8-435d-9834-23cc12ede3ff
      - AZURE_REDIRECT_URI=http://localhost:8087/login/oauth2/code/azure
      - API_BASE_PATH=/api/v1
      - SERVER_PORT=8080
      - MANAGEMENT_PORT=8080
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8087
      - CORS_ALLOWED_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - CORS_ALLOWED_HEADERS=*
      - LOG_LEVEL_ROOT=INFO
      - LOG_LEVEL_SECURITY=INFO
      - LOG_LEVEL_OAUTH2=INFO
      - LOG_LEVEL_APP=INFO
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge
