# Base configuration for Container Login Service
spring:
  application:
    name: container-login-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

# Basic server configuration
server:
  port: ${SERVER_PORT:8080}

# Basic logging configuration
logging:
  level:
    root: INFO
    com.example.loginservice: INFO