server:
  port: ${SERVER_PORT:8080}

spring:
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: ${AZURE_CLIENT_ID:9f6cf3b0-c7fe-4220-86fd-a58ac086a692}
            client-secret: ${AZURE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
              - https://graph.microsoft.com/User.Read
              - https://graph.microsoft.com/Directory.Read.All
              - https://graph.microsoft.com/GroupMember.Read.All
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8082/login/oauth2/code/azure"
            client-name: Azure
        provider:
          azure:
            authorization-uri: https://login.microsoftonline.com/4f402a0a-52d8-435d-9834-23cc12ede3ff/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/4f402a0a-52d8-435d-9834-23cc12ede3ff/oauth2/v2.0/token
            user-info-uri: https://graph.microsoft.com/oidc/userinfo
            jwk-set-uri: https://login.microsoftonline.com/4f402a0a-52d8-435d-9834-23cc12ede3ff/discovery/v2.0/keys
            user-name-attribute: sub

# Actuator configuration for health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    org.springframework.security: ${LOGGING_LEVEL_SECURITY:INFO}
    org.springframework.security.oauth2: ${LOGGING_LEVEL_SECURITY:INFO}
    org.springframework.web.reactive: DEBUG
    ROOT: ${LOGGING_LEVEL_ROOT:INFO}
    com.example.loginservice: ${LOGGING_LEVEL_ROOT:INFO}

# Application-specific configuration
app:
  pagination:
    default-page-size: ${DEFAULT_PAGE_SIZE:20}
    max-page-size: ${MAX_PAGE_SIZE:100}

  # Integration with azure-entra-auth-test service
  external-services:
    azure-entra-auth:
      url: ${AZURE_ENTRA_AUTH_SERVICE_URL:http://container-entra-auth-service.dev.svc.cluster.local:8080}
