apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev
    environment: development
    app.kubernetes.io/name: container-entra-auth
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: container-entra-auth-system
