apiVersion: v1
kind: Secret
metadata:
  name: container-entra-auth-secret
  namespace: dev
  labels:
    app.kubernetes.io/name: container-entra-auth
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: container-entra-auth-system
type: Opaque
data:
  # Azure Entra ID Credentials (base64 encoded)
  # Replace these with your actual base64-encoded values
  # To encode: echo -n "your-value" | base64
  
  AZURE_CLIENT_ID: "REPLACE_WITH_BASE64_ENCODED_CLIENT_ID"
  AZURE_CLIENT_SECRET: "REPLACE_WITH_BASE64_ENCODED_CLIENT_SECRET"
  AZURE_TENANT_ID: "REPLACE_WITH_BASE64_ENCODED_TENANT_ID"

---
# Example of how to create the secret with actual values:
# kubectl create secret generic container-entra-auth-secret \
#   --namespace=dev \
#   --from-literal=AZURE_CLIENT_ID=your-actual-client-id \
#   --from-literal=AZURE_CLIENT_SECRET=your-actual-client-secret \
#   --from-literal=AZURE_TENANT_ID=your-actual-tenant-id
