server:
  port: 8082

spring:
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: ${AZURE_CLIENT_ID:9f6cf3b0-c7fe-4220-86fd-a58ac086a692}
            client-secret: ${AZURE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
              - https://graph.microsoft.com/User.Read
              - https://graph.microsoft.com/Directory.Read.All
              - https://graph.microsoft.com/GroupMember.Read.All
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8082/login/oauth2/code/azure"
            client-name: Azure
        provider:
          azure:
            authorization-uri: https://login.microsoftonline.com/4f402a0a-52d8-435d-9834-23cc12ede3ff/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/4f402a0a-52d8-435d-9834-23cc12ede3ff/oauth2/v2.0/token
            user-info-uri: https://graph.microsoft.com/oidc/userinfo
            jwk-set-uri: https://login.microsoftonline.com/4f402a0a-52d8-435d-9834-23cc12ede3ff/discovery/v2.0/keys
            user-name-attribute: sub
#            authorization-uri: https://login.microsoftonline.com/${AZURE_TENANT_NAME:qcellsces.onmicrosoft.com}/oauth2/v2.0/authorize
#            token-uri: https://login.microsoftonline.com/${AZURE_TENANT_NAME:qcellsces.onmicrosoft.com}/oauth2/v2.0/token
#            user-info-uri: https://graph.microsoft.com/oidc/userinfo
#            jwk-set-uri: https://login.microsoftonline.com/${AZURE_TENANT_NAME:qcellsces.onmicrosoft.com}/discovery/v2.0/keys
#            user-name-attribute: sub

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.web.reactive: DEBUG
    ROOT: DEBUG
