apiVersion: v1
kind: Service
metadata:
  name: container-login-service
  namespace: dev
  labels:
    app.kubernetes.io/name: container-login-service
    app.kubernetes.io/component: service
    app.kubernetes.io/version: "1.0.0"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: container-login-service

# NodePort and LoadBalancer services removed - not required
# External access is handled via kubectl port-forward to ClusterIP service
# This is cleaner and more secure for development/testing
